version: '3.4'

services:
  studentmanagement.api:
    build:
      context: .
      dockerfile: src/StudentManagement.Api/Dockerfile
    depends_on:
      - "sqlserver"
    ports:
        - "5000:80"
  studentdataimporter.api:
    build:
      context: .
      dockerfile: src/StudentDataImporter.Api/Dockerfile
    depends_on:
      - "sqlserver"
    ports:
      - "5001:80"
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=@someThingComplicated1234
      - ACCEPT_EULA=Y

